/**
 * @file lv_barcode.h
 *
 */

#ifndef LV_BARCODE_H
#define LV_BARCODE_H

#ifdef __cplusplus
extern "C" {
#endif

/*********************
 *      INCLUDES
 *********************/
#include "../config/lv_conf_internal.h"
#include "../lv_types.h"
#include "../draw/lv_color.h"
#include "lv_canvas.h"

#if LV_USE_BARCODE

/*********************
 *      DEFINES
 *********************/

/**********************
 *      TYPEDEFS
 **********************/

typedef enum {
    /**
     * Code 128 with GS1 encoding. Strips `[FCN1]` and spaces.
     */
    LV_BARCODE_ENCODING_CODE128_GS1,
    /**
     * Code 128 with raw encoding.
     */
    LV_BARCODE_ENCODING_CODE128_RAW,
} lv_barcode_encoding_t;

LV_ATTRIBUTE_EXTERN_DATA extern const lv_obj_class_t lv_barcode_class;

/**********************
 * GLOBAL PROTOTYPES
 **********************/

/**
 * Create an empty barcode (an `lv_canvas`) object.
 * @param parent point to an object where to create the barcode
 * @return pointer to the created barcode object
 */
lv_obj_t * lv_barcode_create(lv_obj_t * parent);

/**
 * Set the dark color of a barcode object
 * @param obj pointer to barcode object
 * @param color dark color of the barcode
 */
void lv_barcode_set_dark_color(lv_obj_t * obj, lv_color_t color);

/**
 * Set the light color of a barcode object
 * @param obj pointer to barcode object
 * @param color light color of the barcode
 */
void lv_barcode_set_light_color(lv_obj_t * obj, lv_color_t color);

/**
 * Set the scale of a barcode object
 * @param obj pointer to barcode object
 * @param scale scale factor
 */
void lv_barcode_set_scale(lv_obj_t * obj, uint16_t scale);

/**
 * Set the direction of a barcode object
 * @param obj pointer to barcode object
 * @param direction draw direction (`LV_DIR_HOR` or `LB_DIR_VER`)
 */
void lv_barcode_set_direction(lv_obj_t * obj, lv_dir_t direction);

/**
 * Set the tiled mode of a barcode object
 * @param obj pointer to barcode object
 * @param tiled true: tiled mode, false: normal mode (default)
 */
void lv_barcode_set_tiled(lv_obj_t * obj, bool tiled);

/**
 * Set the encoding of a barcode object
 * @param obj pointer to barcode object
 * @param encoding encoding (default is `LV_BARCODE_CODE128_GS1`)
 */
void lv_barcode_set_encoding(lv_obj_t * obj, lv_barcode_encoding_t encoding);

/**
 * Set (store) the data of a barcode object.
 * This stores a copy of the data; the bitmap itself is (re)generated by
 * `lv_barcode_update()`, either automatically (see `lv_barcode_set_auto_update()`,
 * the default) or on the next redraw.
 * @param obj pointer to barcode object
 * @param data data to display as a NUL terminated string
 * @return LV_RESULT_OK: if no error; LV_RESULT_INVALID: on error
 */
lv_result_t lv_barcode_set_data(lv_obj_t * obj, const char * data);

/**
 * (Re)generate the barcode bitmap from the currently stored data.
 * This is done automatically when a property changes unless automatic updating
 * is disabled with `lv_barcode_set_auto_update(obj, false)`, in which case call
 * this after setting the data/scale/direction/encoding to render everything at once.
 * When nothing changed since the last update this is a no-op, so two consecutive
 * calls cost no more than one. Use `lv_barcode_force_update()` to regenerate
 * unconditionally.
 * @param obj pointer to barcode object
 * @return LV_RESULT_OK: if no error; LV_RESULT_INVALID: on error (e.g. no data set)
 */
lv_result_t lv_barcode_update(lv_obj_t * obj);

/**
 * Unconditionally (re)generate the barcode bitmap from the currently stored data,
 * even if nothing is marked as changed. Rarely needed - prefer `lv_barcode_update()`,
 * which skips the work when the bitmap is already up to date.
 * @param obj pointer to barcode object
 * @return LV_RESULT_OK: if no error; LV_RESULT_INVALID: on error (e.g. no data set)
 */
lv_result_t lv_barcode_force_update(lv_obj_t * obj);

/**
 * Enable or disable automatic updating of the bitmap.
 * When enabled (the default) the bitmap is regenerated right away whenever a
 * property that affects it (data, scale, direction, tiled, encoding) changes.
 * When disabled, such changes only mark the bitmap as out of date; call
 * `lv_barcode_update()` to regenerate it. If that is forgotten, the bitmap is
 * regenerated on the next redraw (and a warning is logged). Enabling it while the
 * bitmap is out of date regenerates it immediately.
 * @param obj pointer to barcode object
 * @param enable true: update automatically; false: update manually
 * @return the result of the immediate update triggered by enabling it (the
 *         `lv_barcode_update()` result), otherwise LV_RESULT_OK
 */
lv_result_t lv_barcode_set_auto_update(lv_obj_t * obj, bool enable);

/**
 * Get whether automatic updating of the bitmap is enabled.
 * @param obj pointer to barcode object
 * @return true: automatic updating is enabled; false: it is disabled
 */
bool lv_barcode_get_auto_update(lv_obj_t * obj);

/**
 * Get the data currently stored in a barcode object.
 * @param obj pointer to barcode object
 * @return pointer to the stored data as a NUL terminated string, or NULL if no data is set.
 *         The returned buffer is owned by the barcode object.
 */
const char * lv_barcode_get_data(lv_obj_t * obj);

/**
 * Get the dark color of a barcode object
 * @param obj pointer to barcode object
 * @return dark color of the barcode
 */
lv_color_t lv_barcode_get_dark_color(lv_obj_t * obj);

/**
 * Get the light color of a barcode object
 * @param obj pointer to barcode object
 * @return light color of the barcode
 */
lv_color_t lv_barcode_get_light_color(lv_obj_t * obj);

/**
 * Get the scale of a barcode object
 * @param obj pointer to barcode object
 * @return scale factor
 */
uint16_t lv_barcode_get_scale(lv_obj_t * obj);

/**
 * Get the encoding of a barcode object
 * @param obj pointer to barcode object
 * @return encoding
 */
lv_barcode_encoding_t lv_barcode_get_encoding(const lv_obj_t * obj);

/**********************
 *      MACROS
 **********************/

#endif /*LV_USE_BARCODE*/

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /*LV_BARCODE_H*/
