/**
 * @file lv_qrcode.h
 *
 */

#ifndef LV_QRCODE_H
#define LV_QRCODE_H

#ifdef __cplusplus
extern "C" {
#endif

/*********************
 *      INCLUDES
 *********************/
#include "../config/lv_conf_internal.h"
#if LV_USE_QRCODE

#include "../draw/lv_color.h"
#include "../lv_types.h"
#include "lv_canvas.h"
#include LV_STDBOOL_INCLUDE
#include LV_STDINT_INCLUDE

/*********************
 *      DEFINES
 *********************/

/**********************
 *      TYPEDEFS
 **********************/

LV_ATTRIBUTE_EXTERN_DATA extern const lv_obj_class_t lv_qrcode_class;

/**********************
 * GLOBAL PROTOTYPES
 **********************/

/**
 * Create an empty QR code (an `lv_canvas`) object.
 * @param parent point to an object where to create the QR code
 * @return pointer to the created QR code object
 */
lv_obj_t * lv_qrcode_create(lv_obj_t * parent);

/**
 * Set QR code size.
 * @param obj pointer to a QR code object
 * @param size width and height of the QR code
 */
void lv_qrcode_set_size(lv_obj_t * obj, int32_t size);

/**
 * Set QR code dark color.
 * @param obj pointer to a QR code object
 * @param color dark color of the QR code
 */
void lv_qrcode_set_dark_color(lv_obj_t * obj, lv_color_t color);

/**
 * Set QR code light color.
 * @param obj pointer to a QR code object
 * @param color light color of the QR code
 */
void lv_qrcode_set_light_color(lv_obj_t * obj, lv_color_t color);

/**
 * Set (store) the data of a QR code object from a string.
 * This stores a copy of the data; the bitmap itself is (re)generated by
 * `lv_qrcode_update()`, either automatically (see `lv_qrcode_set_auto_update()`,
 * the default) or on the next redraw.
 * @param obj pointer to a QR code object
 * @param data data to display as a NUL terminated string
 * @return LV_RESULT_OK: if no error; LV_RESULT_INVALID: on error
 */
lv_result_t lv_qrcode_set_data(lv_obj_t * obj, const char * data);

/**
 * Set (store) the data of a QR code object from a (possibly binary) buffer.
 * This stores a copy of the data; the bitmap itself is (re)generated by
 * `lv_qrcode_update()`, either automatically (see `lv_qrcode_set_auto_update()`,
 * the default) or on the next redraw.
 * @note String and binary data share one storage, told apart by a heuristic (a
 *       string ends with a NUL and has no other NUL). A binary payload whose only
 *       NUL byte is its last one is therefore indistinguishable from a string and
 *       is treated as one - that trailing NUL is dropped from the encoded QR code
 *       and from `lv_qrcode_get_data_binary()`. Binary data with no NUL, or with a
 *       NUL anywhere but the very end, is unaffected.
 * @param obj pointer to a QR code object
 * @param data data to display
 * @param data_len length of data in bytes
 * @return LV_RESULT_OK: if no error; LV_RESULT_INVALID: on error
 */
lv_result_t lv_qrcode_set_data_binary(lv_obj_t * obj, const void * data, uint32_t data_len);

/**
 * (Re)generate the QR code bitmap from the currently stored data.
 * This is done automatically when a property changes unless automatic updating
 * is disabled with `lv_qrcode_set_auto_update(obj, false)`, in which case call
 * this after setting the data/size/quiet zone to render everything at once.
 * When nothing changed since the last update this is a no-op, so two consecutive
 * calls cost no more than one. A failed generation is not re-attempted (its outcome
 * only changes when a property changes), but it is remembered: this keeps reporting
 * LV_RESULT_INVALID instead of a success that never happened.
 * @note To regenerate unconditionally (rarely needed, e.g. to retry after an
 *       out-of-memory failure), set the object's `needs_update` field to `true` and
 *       call this function afterwards. That field is private, so it requires
 *       `LV_USE_PRIVATE_API` set to `1` in `lv_conf.h` and `lvgl_private.h` included.
 * @param obj pointer to a QR code object
 * @return LV_RESULT_OK: if no error; LV_RESULT_INVALID: on error (e.g. no data set)
 */
lv_result_t lv_qrcode_update(lv_obj_t * obj);

/**
 * Enable or disable quiet zone.
 * Quiet zone is the area around the QR code where no data is encoded.
 * @param obj pointer to a QR code object
 * @param enable true: enable quiet zone; false: disable quiet zone
 */
void lv_qrcode_set_quiet_zone(lv_obj_t * obj, bool enable);

/**
 * Enable or disable automatic updating of the bitmap.
 * When enabled (the default) the bitmap is regenerated right away whenever a
 * property that affects it (data, size, quiet zone) changes. When disabled,
 * such changes only mark the bitmap as out of date; call `lv_qrcode_update()`
 * to regenerate it. If that is forgotten, the bitmap is regenerated on the next
 * redraw (and a warning is logged).
 * Enabling it while the bitmap is out of date regenerates it immediately.
 * @param obj pointer to a QR code object
 * @param enable true: update automatically; false: update manually
 */
void lv_qrcode_set_auto_update(lv_obj_t * obj, bool enable);

/**
 * Get whether automatic updating of the bitmap is enabled.
 * @param obj pointer to a QR code object
 * @return true: automatic updating is enabled; false: it is disabled
 */
bool lv_qrcode_get_auto_update(lv_obj_t * obj);

/**
 * Get the data currently stored in a QR code object as a string.
 * Only returns the data if it looks like a string, i.e. it is NUL terminated and
 * contains no other NUL byte (which is the case for data set with
 * `lv_qrcode_set_data()`). Otherwise NULL is returned - use
 * `lv_qrcode_get_data_binary()` for binary data.
 * @param obj pointer to a QR code object
 * @return pointer to the stored data as a NUL terminated string, or NULL if no
 *         data is set or the data is not a string.
 *         The returned buffer is owned by the QR code object.
 */
const char * lv_qrcode_get_data(lv_obj_t * obj);

/**
 * Copy the (possibly binary) data currently stored in a QR code object into a
 * caller-provided buffer. Pass `buf == NULL` (or `buf_size == 0`) to only query
 * the stored size without copying.
 * @param obj      pointer to a QR code object
 * @param buf      buffer to copy the data into (may be NULL)
 * @param buf_size size of `buf` in bytes
 * @return the total size of the stored data in bytes. If this is greater than
 *         `buf_size`, only `buf_size` bytes were copied (the data was truncated).
 */
uint32_t lv_qrcode_get_data_binary(lv_obj_t * obj, void * buf, uint32_t buf_size);

/**********************
 *      MACROS
 **********************/

#endif /*LV_USE_QRCODE*/

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /*LV_QRCODE_H*/
