# ESP-IDF component file for make based commands

COMPONENT_SRCDIRS := .
COMPONENT_SRCDIRS += src
COMPONENT_SRCDIRS += src/core
COMPONENT_SRCDIRS += src/draw
COMPONENT_SRCDIRS += src/font
COMPONENT_SRCDIRS += src/gpu
COMPONENT_SRCDIRS += src/hal
COMPONENT_SRCDIRS += src/misc
COMPONENT_SRCDIRS += src/widgets

COMPONENT_ADD_INCLUDEDIRS := .
COMPONENT_ADD_INCLUDEDIRS += src
COMPONENT_ADD_INCLUDEDIRS += src/core
COMPONENT_ADD_INCLUDEDIRS += src/draw
COMPONENT_ADD_INCLUDEDIRS += src/font
COMPONENT_ADD_INCLUDEDIRS += src/gpu
COMPONENT_ADD_INCLUDEDIRS += src/hal
COMPONENT_ADD_INCLUDEDIRS += src/misc
COMPONENT_ADD_INCLUDEDIRS += src/widgets
