/**
 * @file img_conf.h
 *
 */

#if 0 /*Remove this to enable the content (Delete the last #endif too!)*/

#ifndef IMG_CONF_H
#define IMG_CONF_H

/*********************
 *      INCLUDES
 *********************/

/*********************
 *      DEFINES
 *********************/

/* Enable here the used images
 * For example:
 * #define USE_IMG_EXAMPLE       1
 *
 * This is compatible with the images
 * generated by the image converter utility
 * For more information see: www.littlev.hu */

/**********************
 *      TYPEDEFS
 **********************/

/**********************
 * GLOBAL PROTOTYPES
 **********************/

/**********************
 *      MACROS
 **********************/

#endif

#endif /*Remove this to enable the content*/
