CFILES += \
$(LVGL_PATH)/lv_draw/lv_draw_vbasic.c \
$(LVGL_PATH)/lv_draw/lv_draw.c \
$(LVGL_PATH)/lv_draw/lv_draw_rbasic.c \
$(LVGL_PATH)/lv_misc/lv_font.c \
$(LVGL_PATH)/lv_misc/lv_circ.c \
$(LVGL_PATH)/lv_misc/lv_area.c \
$(LVGL_PATH)/lv_misc/lv_task.c \
$(LVGL_PATH)/lv_misc/lv_fs.c \
$(LVGL_PATH)/lv_misc/lv_anim.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_80.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_30_latin_ext_a.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_20_feedback.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_10_cyrillic.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_60_latin_ext_a.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_80_sup.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_30_latin_ext_b.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_80_cyrillic.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_60_cyrillic.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_30_file.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_40_file.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_30_basic.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_10_feedback.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_60_file.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_30_sup.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_40_cyrillic.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_40_latin_ext_a.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_30_feedback.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_20_latin_ext_a.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_60_latin_ext_b.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_80_file.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_60_feedback.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_40_feedback.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_20_cyrillic.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_60_sup.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_10_sup.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_20_sup.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_10_basic.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_30_cyrillic.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_60_basic.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_80_latin_ext_a.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_60.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_40_sup.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_80_feedback.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_20.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_20_latin_ext_b.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_10.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_20_file.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_40.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_30.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_20_basic.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_40_basic.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_40_latin_ext_b.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_80_basic.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_10_latin_ext_b.c \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_10_file.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_80_latin_ext_b.c \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_10_latin_ext_a.c \
$(LVGL_PATH)/lv_misc/lv_mem.c \
$(LVGL_PATH)/lv_misc/lv_templ.c \
$(LVGL_PATH)/lv_misc/lv_ll.c \
$(LVGL_PATH)/lv_misc/lv_color.c \
$(LVGL_PATH)/lv_misc/lv_txt.c \
$(LVGL_PATH)/lv_misc/lv_ufs.c \
$(LVGL_PATH)/lv_misc/lv_trigo.c \
$(LVGL_PATH)/lv_objx/lv_roller.c \
$(LVGL_PATH)/lv_objx/lv_ddlist.c \
$(LVGL_PATH)/lv_objx/lv_page.c \
$(LVGL_PATH)/lv_objx/lv_list.c \
$(LVGL_PATH)/lv_objx/lv_ta.c \
$(LVGL_PATH)/lv_objx/lv_tabview.c \
$(LVGL_PATH)/lv_objx/lv_btn.c \
$(LVGL_PATH)/lv_objx/lv_kb.c \
$(LVGL_PATH)/lv_objx/lv_bar.c \
$(LVGL_PATH)/lv_objx/lv_lmeter.c \
$(LVGL_PATH)/lv_objx/lv_cb.c \
$(LVGL_PATH)/lv_objx/lv_slider.c \
$(LVGL_PATH)/lv_objx/lv_win.c \
$(LVGL_PATH)/lv_objx/lv_label.c \
$(LVGL_PATH)/lv_objx/lv_line.c \
$(LVGL_PATH)/lv_objx/lv_mbox.c \
$(LVGL_PATH)/lv_objx/lv_sw.c \
$(LVGL_PATH)/lv_objx/lv_led.c \
$(LVGL_PATH)/lv_objx/lv_chart.c \
$(LVGL_PATH)/lv_objx/lv_img.c \
$(LVGL_PATH)/lv_objx/lv_gauge.c \
$(LVGL_PATH)/lv_objx/lv_objx_templ.c \
$(LVGL_PATH)/lv_objx/lv_btnm.c \
$(LVGL_PATH)/lv_objx/lv_cont.c \
$(LVGL_PATH)/lv_hal/lv_hal_indev.c \
$(LVGL_PATH)/lv_hal/lv_hal_tick.c \
$(LVGL_PATH)/lv_hal/lv_hal_disp.c \
$(LVGL_PATH)/lv_themes/lv_theme_alien.c \
$(LVGL_PATH)/lv_themes/lv_theme_templ.c \
$(LVGL_PATH)/lv_themes/lv_theme.c \
$(LVGL_PATH)/lv_themes/lv_theme_night.c \
$(LVGL_PATH)/lv_themes/lv_theme_default.c \
$(LVGL_PATH)/lv_obj/lv_group.c \
$(LVGL_PATH)/lv_obj/lv_vdb.c \
$(LVGL_PATH)/lv_obj/lv_obj.c \
$(LVGL_PATH)/lv_obj/lv_style.c \
$(LVGL_PATH)/lv_obj/lv_indev.c \
$(LVGL_PATH)/lv_obj/lv_refr.c 


