OBJFILES += \
$(LVGL_PATH)/lv_draw/lv_draw_vbasic.o \
$(LVGL_PATH)/lv_draw/lv_draw.o \
$(LVGL_PATH)/lv_draw/lv_draw_rbasic.o \
$(LVGL_PATH)/lv_misc/lv_font.o \
$(LVGL_PATH)/lv_misc/lv_circ.o \
$(LVGL_PATH)/lv_misc/lv_area.o \
$(LVGL_PATH)/lv_misc/lv_task.o \
$(LVGL_PATH)/lv_misc/lv_fs.o \
$(LVGL_PATH)/lv_misc/lv_anim.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_80.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_30_latin_ext_a.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_20_feedback.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_10_cyrillic.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_60_latin_ext_a.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_80_sup.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_30_latin_ext_b.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_80_cyrillic.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_60_cyrillic.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_30_file.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_40_file.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_30_basic.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_10_feedback.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_60_file.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_30_sup.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_40_cyrillic.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_40_latin_ext_a.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_30_feedback.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_20_latin_ext_a.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_60_latin_ext_b.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_80_file.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_60_feedback.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_40_feedback.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_20_cyrillic.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_60_sup.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_10_sup.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_20_sup.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_10_basic.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_30_cyrillic.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_60_basic.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_80_latin_ext_a.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_60.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_40_sup.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_80_feedback.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_20.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_20_latin_ext_b.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_10.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_20_file.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_40.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_30.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_20_basic.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_40_basic.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_40_latin_ext_b.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_80_basic.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_10_latin_ext_b.o \
$(LVGL_PATH)/lv_misc/lv_fonts/symbol_10_file.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_80_latin_ext_b.o \
$(LVGL_PATH)/lv_misc/lv_fonts/dejavu_10_latin_ext_a.o \
$(LVGL_PATH)/lv_misc/lv_mem.o \
$(LVGL_PATH)/lv_misc/lv_templ.o \
$(LVGL_PATH)/lv_misc/lv_ll.o \
$(LVGL_PATH)/lv_misc/lv_color.o \
$(LVGL_PATH)/lv_misc/lv_txt.o \
$(LVGL_PATH)/lv_misc/lv_ufs.o \
$(LVGL_PATH)/lv_misc/lv_trigo.o \
$(LVGL_PATH)/lv_objx/lv_roller.o \
$(LVGL_PATH)/lv_objx/lv_ddlist.o \
$(LVGL_PATH)/lv_objx/lv_page.o \
$(LVGL_PATH)/lv_objx/lv_list.o \
$(LVGL_PATH)/lv_objx/lv_ta.o \
$(LVGL_PATH)/lv_objx/lv_tabview.o \
$(LVGL_PATH)/lv_objx/lv_btn.o \
$(LVGL_PATH)/lv_objx/lv_kb.o \
$(LVGL_PATH)/lv_objx/lv_bar.o \
$(LVGL_PATH)/lv_objx/lv_lmeter.o \
$(LVGL_PATH)/lv_objx/lv_cb.o \
$(LVGL_PATH)/lv_objx/lv_slider.o \
$(LVGL_PATH)/lv_objx/lv_win.o \
$(LVGL_PATH)/lv_objx/lv_label.o \
$(LVGL_PATH)/lv_objx/lv_line.o \
$(LVGL_PATH)/lv_objx/lv_mbox.o \
$(LVGL_PATH)/lv_objx/lv_sw.o \
$(LVGL_PATH)/lv_objx/lv_led.o \
$(LVGL_PATH)/lv_objx/lv_chart.o \
$(LVGL_PATH)/lv_objx/lv_img.o \
$(LVGL_PATH)/lv_objx/lv_gauge.o \
$(LVGL_PATH)/lv_objx/lv_objx_templ.o \
$(LVGL_PATH)/lv_objx/lv_btnm.o \
$(LVGL_PATH)/lv_objx/lv_cont.o \
$(LVGL_PATH)/lv_hal/lv_hal_indev.o \
$(LVGL_PATH)/lv_hal/lv_hal_tick.o \
$(LVGL_PATH)/lv_hal/lv_hal_disp.o \
$(LVGL_PATH)/lv_themes/lv_theme_alien.o \
$(LVGL_PATH)/lv_themes/lv_theme_templ.o \
$(LVGL_PATH)/lv_themes/lv_theme.o \
$(LVGL_PATH)/lv_themes/lv_theme_night.o \
$(LVGL_PATH)/lv_themes/lv_theme_default.o \
$(LVGL_PATH)/lv_obj/lv_group.o \
$(LVGL_PATH)/lv_obj/lv_vdb.o \
$(LVGL_PATH)/lv_obj/lv_obj.o \
$(LVGL_PATH)/lv_obj/lv_style.o \
$(LVGL_PATH)/lv_obj/lv_indev.o \
$(LVGL_PATH)/lv_obj/lv_refr.o 


