set(LVGL_VERSION_MAJOR 8 PARENT_SCOPE)
set(LVGL_VERSION_MINOR 0 PARENT_SCOPE)
set(LVGL_VERSION_PATCH 3 PARENT_SCOPE)
set(LVGL_VERSION_INFO "dev" PARENT_SCOPE)

set(LVGL_VERSION "${LVGL_VERSION_MAJOR}.${LVGL_VERSION_MINOR}.${LVGL_VERSION_PATCH}")