set(LVGL_VERSION_MAJOR "9")
set(LVGL_VERSION_MINOR "3")
set(LVGL_VERSION_PATCH "0")
set(LVGL_VERSION_INFO  "dev")

set(LVGL_VERSION ${LVGL_VERSION_MAJOR}.${LVGL_VERSION_MINOR}.${LVGL_VERSION_PATCH}) # This is a CMake variable
set(ENV{LVGL_VERSION} ${LVGL_VERSION}) # This is exported Environmental variable
set(LVGL_SOVERSION ${LVGL_VERSION_MAJOR})
