#define LV_MEM_SIZE         8388608
#define LV_USE_DRAW_MASKS       1
#define LV_SHADOW_CACHE_SIZE    10240
#define LV_IMG_CACHE_DEF_SIZE   32
#define LV_USE_LOG              1
#define LV_LOG_LEVEL            LV_LOG_LEVEL_TRACE
#define LV_LOG_PRINTF           1
#define LV_USE_FONT_SUBPX       1
#define LV_FONT_SUBPX_BGR       1
#define LV_USE_PERF_MONITOR     1
#define LV_USE_ASSERT_NULL      1
#define LV_USE_ASSERT_MALLOC    1
#define LV_USE_ASSERT_MEM_INTEGRITY     1
#define LV_USE_ASSERT_OBJ               1
#define LV_USE_ASSERT_STYLE             1
#define LV_USE_USER_DATA                1
#define LV_USE_LARGE_COORD      1

#define LV_FONT_MONTSERRAT_8    1
#define LV_FONT_MONTSERRAT_10   1
#define LV_FONT_MONTSERRAT_12   1
#define LV_FONT_MONTSERRAT_14   1
#define LV_FONT_MONTSERRAT_16   1
#define LV_FONT_MONTSERRAT_18   1
#define LV_FONT_MONTSERRAT_20   1
#define LV_FONT_MONTSERRAT_22   1
#define LV_FONT_MONTSERRAT_24   1
#define LV_FONT_MONTSERRAT_26   1
#define LV_FONT_MONTSERRAT_28   1
#define LV_FONT_MONTSERRAT_30   1
#define LV_FONT_MONTSERRAT_32   1
#define LV_FONT_MONTSERRAT_34   1
#define LV_FONT_MONTSERRAT_36   1
#define LV_FONT_MONTSERRAT_38   1
#define LV_FONT_MONTSERRAT_40   1
#define LV_FONT_MONTSERRAT_42   1
#define LV_FONT_MONTSERRAT_44   1
#define LV_FONT_MONTSERRAT_46   1
#define LV_FONT_MONTSERRAT_48   1
#define LV_FONT_MONTSERRAT_12_SUBPX         1
#define LV_FONT_MONTSERRAT_28_COMPRESSED    1
#define LV_FONT_DEJAVU_16_PERSIAN_HEBREW    1
#define LV_FONT_SIMSUN_16_CJK   1
#define LV_FONT_UNSCII_8        1
#define LV_FONT_UNSCII_16       1
#define LV_FONT_DEFAULT         &lv_font_montserrat_14
#define LV_FONT_FMT_TXT_LARGE   1
#define LV_USE_FONT_COMPRESSED  1
#define LV_USE_BIDI 1
#define LV_USE_ARABIC_PERSIAN_CHARS 1
#define LV_USE_PERF_MONITOR         1
#define LV_USE_MEM_MONITOR          1
#define LV_LABEL_TEXT_SELECTION     1

#define LV_USE_FLEX 1
#define LV_USE_GRID 1

#define LV_USE_FS_STDIO     1
#define LV_FS_STDIO_LETTER  'A'
#define LV_USE_FS_POSIX     1
#define LV_FS_POSIX_LETTER  'B'

#define LV_USE_PNG      1
#define LV_USE_BMP      1
#define LV_USE_SJPG     1
#define LV_USE_GIF      1
#define LV_USE_QRCODE   1
#define LV_USE_BARCODE  1
#define LV_USE_FRAGMENT 1
#define LV_USE_IMGFONT  1
#define LV_USE_IME_PINYIN   1
#define LV_USE_MSG          1
#define LV_USE_FILE_EXPLORER    1
#define LV_USE_TINY_TTF 1


#define LV_BUILD_EXAMPLES       1
#define LV_USE_DEMO_WIDGETS     1
#define LV_USE_DEMO_STRESS      1

