#ifndef LV_TEST_CONF_OPENGLES_H
#define LV_TEST_CONF_OPENGLES_H

#ifdef LV_DRAW_BUF_STRIDE_ALIGN
    #undef LV_DRAW_BUF_STRIDE_ALIGN
#endif

#define LV_DRAW_BUF_STRIDE_ALIGN 1
#define LV_DRAW_BUF_ALIGN 4

#define LV_USE_OPENGLES 1
#define LV_USE_DRAW_OPENGLES 1

#endif /*LV_TEST_CONF_OPENGLES_H*/
