#LVGL MicroPython testing definitions (error codes, etc.) common for Python3 and MicroPython

RESULT_OK = 0

ERROR_BINDING_SYSTEM_FAULT = 255
ERROR_NOT_ALL_TESTS_PASSED = 254
ERROR_TESTCASE_NOT_GIVEN   = 253
ERROR_TESTCASE_NOT_FOUND   = 252
ERROR_TESTCASE_FAILED      = 251

#ERROR_SUBTEST_1_FAILED     = 241
#ERROR_SUBTEST_2_FAILED     = 242
#ERROR_SUBTEST_3_FAILED     = 243
#ERROR_SUBTEST_4_FAILED     = 244

