#LVGL MicroPython testing definitions (error codes, etc.) common for Python3 and MicroPython

RESULT_OK = 0
ERROR_TESTCASE_FAILED      = 255
ERROR_TESTCASE_NOT_FOUND   = 254
ERROR_TESTCASE_NOT_GIVEN   = 253
ERROR_BINDING_SYSTEM_FAULT = 252
ERROR_NOT_ALL_TESTS_PASSED = 251
