"""
Auto-generated event constants from LVGL headers.

Do not edit manually. Regenerate from the GDB script root with:
    python3 scripts/generate_all.py
"""

EVENT_CODE_NAMES = {
    0: "ALL",
    1: "PRESSED",
    2: "PRESSING",
    3: "PRESS_LOST",
    4: "SHORT_CLICKED",
    5: "SINGLE_CLICKED",
    6: "DOUBLE_CLICKED",
    7: "TRIPLE_CLICKED",
    8: "LONG_PRESSED",
    9: "LONG_PRESSED_REPEAT",
    10: "CLICKED",
    11: "RELEASED",
    12: "SCROLL_BEGIN",
    13: "SCROLL_THROW_BEGIN",
    14: "SCROLL_END",
    15: "SCROLL",
    16: "GESTURE",
    17: "GESTURE_UP",
    18: "GESTURE_DOWN",
    19: "GESTURE_LEFT",
    20: "GESTURE_RIGHT",
    21: "KEY",
    22: "ROTARY",
    23: "FOCUSED",
    24: "DEFOCUSED",
    25: "LEAVE",
    26: "HIT_TEST",
    27: "INDEV_RESET",
    28: "HOVER_OVER",
    29: "HOVER_LEAVE",
    30: "COVER_CHECK",
    31: "REFR_EXT_DRAW_SIZE",
    32: "DRAW_MAIN_BEGIN",
    33: "DRAW_MAIN",
    34: "DRAW_MAIN_END",
    35: "DRAW_POST_BEGIN",
    36: "DRAW_POST",
    37: "DRAW_POST_END",
    38: "DRAW_TASK_ADDED",
    39: "VALUE_CHANGED",
    40: "INSERT",
    41: "REFRESH",
    42: "READY",
    43: "CANCEL",
    44: "STATE_CHANGED",
    45: "CHECKED",
    46: "UNCHECKED",
    47: "CREATE",
    48: "DELETE",
    49: "CHILD_CHANGED",
    50: "CHILD_CREATED",
    51: "CHILD_DELETED",
    52: "SCREEN_UNLOAD_START",
    53: "SCREEN_LOAD_START",
    54: "SCREEN_LOADED",
    55: "SCREEN_UNLOADED",
    56: "SIZE_CHANGED",
    57: "STYLE_CHANGED",
    58: "GET_SELF_SIZE",
    59: "INVALIDATE_AREA",
    60: "RESOLUTION_CHANGED",
    61: "COLOR_FORMAT_CHANGED",
    62: "REFR_REQUEST",
    63: "REFR_START",
    64: "REFR_READY",
    65: "RENDER_START",
    66: "RENDER_READY",
    67: "FLUSH_START",
    68: "FLUSH_FINISH",
    69: "FLUSH_WAIT_START",
    70: "FLUSH_WAIT_FINISH",
    71: "SYNC_START",
    72: "SYNC_FINISH",
    73: "SYNC_WAIT_START",
    74: "SYNC_WAIT_FINISH",
    75: "VSYNC",
    76: "VSYNC_REQUEST",
    77: "TRANSLATION_LANGUAGE_CHANGED",
    32767: "LAST_CUSTOM",
}
