/**
 * @file lv_example_widgets.h
 *
 * Meta-header that pulls in every per-widget example header. Add a new
 * widget's header below alphabetically; per-widget headers themselves are
 * regenerated by `scripts/generate_examples.py` from the XML examples in
 * each widget's subtree, with a manual-prototype zone preserved for
 * C-only examples.
 */

#ifndef LV_EXAMPLE_WIDGETS_H
#define LV_EXAMPLE_WIDGETS_H

#ifdef __cplusplus
extern "C" {
#endif

/*********************
 *      INCLUDES
 *********************/

#include "animimg/lv_example_animimg.h"
#include "arc/lv_example_arc.h"
#include "arclabel/lv_example_arclabel.h"
#include "bar/lv_example_bar.h"
#include "button/lv_example_button.h"
#include "buttonmatrix/lv_example_buttonmatrix.h"
#include "calendar/lv_example_calendar.h"
#include "canvas/lv_example_canvas.h"
#include "chart/lv_example_chart.h"
#include "checkbox/lv_example_checkbox.h"
#include "dropdown/lv_example_dropdown.h"
#include "image/lv_example_image.h"
#include "imagebutton/lv_example_imagebutton.h"
#include "keyboard/lv_example_keyboard.h"
#include "label/lv_example_label.h"
#include "led/lv_example_led.h"
#include "line/lv_example_line.h"
#include "list/lv_example_list.h"
#include "lottie/lv_example_lottie.h"
#include "menu/lv_example_menu.h"
#include "msgbox/lv_example_msgbox.h"
#include "obj/lv_example_obj.h"
#include "roller/lv_example_roller.h"
#include "scale/lv_example_scale.h"
#include "slider/lv_example_slider.h"
#include "span/lv_example_span.h"
#include "spinbox/lv_example_spinbox.h"
#include "spinner/lv_example_spinner.h"
#include "switch/lv_example_switch.h"
#include "table/lv_example_table.h"
#include "tabview/lv_example_tabview.h"
#include "textarea/lv_example_textarea.h"
#include "tileview/lv_example_tileview.h"
#include "win/lv_example_win.h"

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /*LV_EXAMPLE_WIDGETS_H*/
