#!/usr/bin/env python3

import os
import re
import subprocess
import sys
import argparse
from typing import List, Union

DIR_SCRIPTS = os.path.dirname(os.path.abspath(__file__))
DIR_REPO_ROOT = os.path.dirname(DIR_SCRIPTS)

# Files that are generated from the Kconfig tree and from `lv_version.h`.
GENERATORS = [
    (['scripts', 'generators', 'config_files.py'],
     ['Kconfig', 'lv_conf_template.h',
      'include/lvgl/config/lv_conf_internal.h',
      'include/lvgl/config/lv_conf_kconfig.h']),
    (['scripts', 'generate_sbom.py'],
     ['sbom/lvgl.spdx.json']),
]

# Version bumps that are not automated, printed as a reminder at the end.
MANUAL_STEPS = [
    "env_support/cmsis-pack (LVGL.lvgl.pdsc, LVGL.pidx, lv_conf_cmsis.h)",
    "the widgets demo renders the version string, so tests/ref_imgs*/demo_widgets.png have to be regenerated by running the tests",
]


def get_arg():
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter, description=""
                                     "Apply the specified version to affected source files. Eg.:\n"
                                     " python3 update_version.py 9.1.2-dev\n"
                                     " python3 update_version.py 9.2.0"
                                     )
    parser.add_argument('version', metavar='version', type=str,
                        help='The version to apply')
    parser.add_argument('--skip-generate', action='store_true',
                        help='Do not regenerate the files derived from the Kconfig tree')

    return parser.parse_args()


class Version:
    RE_PATTERN = r"(\d+)\.(\d+)\.(\d+)(-[\w\d]+)?"

    def __init__(self, user_input: str):

        if not re.match(r'^' + self.RE_PATTERN + r'$', user_input):
            raise Exception(f"Invalid version format: {user_input}")

        groups = re.search(self.RE_PATTERN, user_input).groups()

        self.major = groups[0]
        self.minor = groups[1]
        self.patch = groups[2]
        self.info = groups[3].lstrip('-') if groups[3] else ""

        self.is_release = len(self.info) == 0
        self.as_string = user_input

    @property
    def without_info(self):
        return f"{self.major}.{self.minor}.{self.patch}"

    def __str__(self):
        return self.as_string


class RepoFileVersionReplacer:

    def __init__(self, relative_path_segments: List[str], expected_occurrences: int):
        self.path_relative = os.path.join(*relative_path_segments)
        self.path = os.path.join(DIR_REPO_ROOT, self.path_relative)
        self.expected_occurrences = expected_occurrences

    def applyVersionToLine(self, line: str, version: Version) -> Union[str, None]:
        return None

    def applyVersion(self, version: Version):
        with open(self.path, 'r', encoding='utf-8') as file:
            lines = file.readlines()

        occurrences = 0
        for i, line in enumerate(lines):
            line_with_version = self.applyVersionToLine(line, version)
            if line_with_version:
                lines[i] = line_with_version
                occurrences += 1

        # not perfect, but will catch obvious pitfalls
        if occurrences != self.expected_occurrences:
            raise Exception(f"Replaced {occurrences} line(s) in {self.path_relative}, "
                            f"expected {self.expected_occurrences}")

        with open(self.path, 'w', encoding='utf-8', newline='') as file:
            file.writelines(lines)


class PrefixReplacer(RepoFileVersionReplacer):

    def __init__(self, relative_path_segments: List[str], prefix: str, expected_occurrences=1):
        super().__init__(relative_path_segments, expected_occurrences)
        self.prefix = prefix

    def applyVersionToLine(self, line: str, version: Version):
        pattern = r'(' + re.escape(self.prefix) + ')' + Version.RE_PATTERN
        repl = r'\g<1>' + str(version)
        replaced, n = re.subn(pattern, repl, line)
        return replaced if n > 0 else None


class MacroReplacer(RepoFileVersionReplacer):
    def __init__(self, relative_path_segments: List[str]):
        super().__init__(relative_path_segments, 4)

    def applyVersionToLine(self, line: str, version: Version):
        targets = {
            'LVGL_VERSION_MAJOR': version.major,
            'LVGL_VERSION_MINOR': version.minor,
            'LVGL_VERSION_PATCH': version.patch,
            'LVGL_VERSION_INFO': version.info,
        }

        for key, val in targets.items():
            pattern = self.getPattern(key)
            repl = self.getReplacement(val)
            replaced, n = re.subn(pattern, repl, line)
            if n > 0:
                return replaced

        return None

    def getPattern(self, key: str):
        return r'(^#define ' + key + r' +).+'

    def getReplacement(self, val: str):
        if not val.isnumeric():
            val = f'"{val}"'

        return r'\g<1>' + val


class CmakeReplacer(MacroReplacer):
    def getPattern(self, key: str):
        return r'(^set\(' + key + r' +")([^"]*)(.+)'

    def getReplacement(self, val: str):
        return r'\g<1>' + val + r'\g<3>'


class KconfigReplacer(RepoFileVersionReplacer):
    SYMBOLS = ('LVGL_VERSION_MAJOR', 'LVGL_VERSION_MINOR', 'LVGL_VERSION_PATCH')

    def __init__(self, relative_path_segments: List[str]):
        super().__init__(relative_path_segments, len(self.SYMBOLS))
        self.symbol = None

    def applyVersion(self, version: Version):
        self.symbol = None
        super().applyVersion(version)

    def applyVersionToLine(self, line: str, version: Version):
        config = re.match(r'^\s*config\s+(\w+)', line)
        if config:
            self.symbol = config.group(1)
            return None

        if self.symbol not in self.SYMBOLS:
            return None

        val = {
            'LVGL_VERSION_MAJOR': version.major,
            'LVGL_VERSION_MINOR': version.minor,
            'LVGL_VERSION_PATCH': version.patch,
        }[self.symbol]

        replaced, n = re.subn(r'(^\s*default\s+)\d+', r'\g<1>' + val, line)
        if n == 0:
            return None

        self.symbol = None
        return replaced


def run_generators():
    """Regenerate the files derived from the Kconfig tree and lv_version.h."""

    for path_segments, outputs in GENERATORS:
        path_relative = os.path.join(*path_segments)
        print(f"  - {path_relative}")
        for output in outputs:
            print(f"      {output}")

        result = subprocess.run([sys.executable, os.path.join(DIR_REPO_ROOT, path_relative)],
                                cwd=DIR_REPO_ROOT, capture_output=True, text=True)
        if result.returncode != 0:
            print(result.stdout, end='')
            print(result.stderr, end='', file=sys.stderr)
            raise Exception(f"{path_relative} failed with exit code {result.returncode}")


def verify_generated(version: Version):
    """Make sure the generated files really picked up the new version."""

    expected = {
        'lv_conf_template.h': f"Configuration file for v{version.without_info}",
        os.path.join('sbom', 'lvgl.spdx.json'): f'"software_packageVersion": "{version}"',
        'Kconfig': f"config LVGL_VERSION_MAJOR\n\tint\n\tdefault {version.major}",
        'Kconfig': f"config LVGL_VERSION_MINOR\n\tint\n\tdefault {version.minor}",
        'Kconfig': f"config LVGL_VERSION_PATCH\n\tint\n\tdefault {version.patch}",
    }

    for path_relative, needle in expected.items():
        with open(os.path.join(DIR_REPO_ROOT, path_relative), 'r', encoding='utf-8') as file:
            if needle not in file.read():
                raise Exception(f"{path_relative} does not contain {needle!r} after generation")


if __name__ == '__main__':
    args = get_arg()

    version = Version(args.version)
    print(f"Applying version {version} to:")

    targets = [
        MacroReplacer(['include', 'lvgl', 'lv_version.h']),
        CmakeReplacer(['env_support', 'cmake', 'version.cmake']),
        KconfigReplacer(['env_support', 'kconfig', 'Kconfig.build']),
    ]

    if version.is_release:
        targets.extend([
            PrefixReplacer(['library.json'], '"version": "'),
            PrefixReplacer(['library.properties'], 'version='),
        ])

    for target in targets:
        print(f"  - {target.path_relative}")
        target.applyVersion(version)

    if args.skip_generate:
        print("\nSkipping the generated files")
    else:
        print("\nRegenerating:")
        run_generators()
        verify_generated(version)

    print("\nStill to do by hand:")
    for step in MANUAL_STEPS:
        print(f"  - {step}")
