set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv)

find_program(CMAKE_C_COMPILER riscv32-esp-elf-gcc REQUIRED)
find_program(CMAKE_ASM_COMPILER riscv32-esp-elf-gcc REQUIRED)

set(CMAKE_C_FLAGS_INIT "-march=rv32imc_zicsr_zifencei")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-nostartfiles")

set(LV_MEM_TEST_NEEDS_ROM_STUBS ON)
set(LV_MEM_TEST_EXTRA_LIBS gcc c)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
