#ifndef LV_SYMBOL_DEF_H
#define LV_SYMBOL_DEF_H
/* clang-format off */

#ifdef __cplusplus
extern "C" {
#endif
#ifdef LV_CONF_INCLUDE_SIMPLE
#include "lv_conf.h"
#else
#include "../../../lv_conf.h"
#endif

#define LV_SYMBOL_GLYPH_FIRST  0xF800
#define LV_SYMBOL_AUDIO           _LV_SYMBOL_VALUE3(EF,A0,80)
#define LV_SYMBOL_VIDEO           _LV_SYMBOL_VALUE3(EF,A0,81)
#define LV_SYMBOL_LIST            _LV_SYMBOL_VALUE3(EF,A0,82)
#define LV_SYMBOL_OK              _LV_SYMBOL_VALUE3(EF,A0,83)
#define LV_SYMBOL_CLOSE           _LV_SYMBOL_VALUE3(EF,A0,84)
#define LV_SYMBOL_POWER           _LV_SYMBOL_VALUE3(EF,A0,85)
#define LV_SYMBOL_SETTINGS        _LV_SYMBOL_VALUE3(EF,A0,86)
#define LV_SYMBOL_TRASH           _LV_SYMBOL_VALUE3(EF,A0,87)
#define LV_SYMBOL_HOME            _LV_SYMBOL_VALUE3(EF,A0,88)
#define LV_SYMBOL_DOWNLOAD        _LV_SYMBOL_VALUE3(EF,A0,89)
#define LV_SYMBOL_DRIVE           _LV_SYMBOL_VALUE3(EF,A0,8A)
#define LV_SYMBOL_REFRESH         _LV_SYMBOL_VALUE3(EF,A0,8B)
#define LV_SYMBOL_MUTE            _LV_SYMBOL_VALUE3(EF,A0,8C)
#define LV_SYMBOL_VOLUME_MID      _LV_SYMBOL_VALUE3(EF,A0,8D)
#define LV_SYMBOL_VOLUME_MAX      _LV_SYMBOL_VALUE3(EF,A0,8E)
#define LV_SYMBOL_IMAGE           _LV_SYMBOL_VALUE3(EF,A0,8F)
#define LV_SYMBOL_EDIT            _LV_SYMBOL_VALUE3(EF,A0,90)
#define LV_SYMBOL_PREV            _LV_SYMBOL_VALUE3(EF,A0,91)
#define LV_SYMBOL_PLAY            _LV_SYMBOL_VALUE3(EF,A0,92)
#define LV_SYMBOL_PAUSE           _LV_SYMBOL_VALUE3(EF,A0,93)
#define LV_SYMBOL_STOP            _LV_SYMBOL_VALUE3(EF,A0,94)
#define LV_SYMBOL_NEXT            _LV_SYMBOL_VALUE3(EF,A0,95)
#define LV_SYMBOL_EJECT           _LV_SYMBOL_VALUE3(EF,A0,96)
#define LV_SYMBOL_LEFT            _LV_SYMBOL_VALUE3(EF,A0,97)
#define LV_SYMBOL_RIGHT           _LV_SYMBOL_VALUE3(EF,A0,98)
#define LV_SYMBOL_PLUS            _LV_SYMBOL_VALUE3(EF,A0,99)
#define LV_SYMBOL_MINUS           _LV_SYMBOL_VALUE3(EF,A0,9A)
#define LV_SYMBOL_WARNING         _LV_SYMBOL_VALUE3(EF,A0,9B)
#define LV_SYMBOL_SHUFFLE         _LV_SYMBOL_VALUE3(EF,A0,9C)
#define LV_SYMBOL_UP              _LV_SYMBOL_VALUE3(EF,A0,9D)
#define LV_SYMBOL_DOWN            _LV_SYMBOL_VALUE3(EF,A0,9E)
#define LV_SYMBOL_LOOP            _LV_SYMBOL_VALUE3(EF,A0,9F)
#define LV_SYMBOL_DIRECTORY       _LV_SYMBOL_VALUE3(EF,A0,A0)
#define LV_SYMBOL_UPLOAD          _LV_SYMBOL_VALUE3(EF,A0,A1)
#define LV_SYMBOL_CALL            _LV_SYMBOL_VALUE3(EF,A0,A2)
#define LV_SYMBOL_CUT             _LV_SYMBOL_VALUE3(EF,A0,A3)
#define LV_SYMBOL_COPY            _LV_SYMBOL_VALUE3(EF,A0,A4)
#define LV_SYMBOL_SAVE            _LV_SYMBOL_VALUE3(EF,A0,A5)
#define LV_SYMBOL_CHARGE          _LV_SYMBOL_VALUE3(EF,A0,A6)
#define LV_SYMBOL_BELL            _LV_SYMBOL_VALUE3(EF,A0,A7)
#define LV_SYMBOL_KEYBOARD        _LV_SYMBOL_VALUE3(EF,A0,A8)
#define LV_SYMBOL_GPS             _LV_SYMBOL_VALUE3(EF,A0,A9)
#define LV_SYMBOL_FILE            _LV_SYMBOL_VALUE3(EF,A0,AA)
#define LV_SYMBOL_WIFI            _LV_SYMBOL_VALUE3(EF,A0,AB)
#define LV_SYMBOL_BATTERY_FULL    _LV_SYMBOL_VALUE3(EF,A0,AC)
#define LV_SYMBOL_BATTERY_3       _LV_SYMBOL_VALUE3(EF,A0,AD)
#define LV_SYMBOL_BATTERY_2       _LV_SYMBOL_VALUE3(EF,A0,AE)
#define LV_SYMBOL_BATTERY_1       _LV_SYMBOL_VALUE3(EF,A0,AF)
#define LV_SYMBOL_BATTERY_EMPTY   _LV_SYMBOL_VALUE3(EF,A0,B0)
#define LV_SYMBOL_BLUETOOTH       _LV_SYMBOL_VALUE3(EF,A0,B1)
#define LV_SYMBOL_GLYPH_LAST   0xF831
#define LV_SYMBOL_DUMMY           _LV_SYMBOL_VALUE3(EF,A3,BF)       /*Invalid symbol at (U+F831). If written before a string then `lv_img` will show it as a label*/

#define _LV_SYMBOL_VALUE3(x, y, z) (0x ## z ## y ## x)
#define _LV_SYMBOL_NUMSTR(sym) LV_ ## sym ## _NUMSTR = sym

enum
{
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_AUDIO),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_VIDEO),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_LIST),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_OK),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_CLOSE),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_POWER),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_SETTINGS),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_TRASH),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_HOME),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_DOWNLOAD),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_DRIVE),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_REFRESH),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_MUTE),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_VOLUME_MID),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_VOLUME_MAX),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_IMAGE),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_EDIT),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_PREV),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_PLAY),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_PAUSE),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_STOP),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_NEXT),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_EJECT),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_LEFT),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_RIGHT),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_PLUS),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_MINUS),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_WARNING),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_SHUFFLE),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_UP),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_DOWN),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_LOOP),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_DIRECTORY),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_UPLOAD),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_CALL),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_CUT),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_COPY),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_SAVE),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_CHARGE),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_BELL),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_KEYBOARD),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_GPS),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_FILE),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_WIFI),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_BATTERY_FULL),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_BATTERY_3),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_BATTERY_2),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_BATTERY_1),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_BATTERY_EMPTY),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_BLUETOOTH),
    _LV_SYMBOL_NUMSTR(LV_SYMBOL_DUMMY),
};

#undef _LV_SYMBOL_VALUE3

#define _LV_SYMBOL_STR_(x) #x
#define _LV_SYMBOL_STR(x) _LV_SYMBOL_STR_(x)
#define _LV_SYMBOL_CHAR(c) \x ## c
#define _LV_SYMBOL_VALUE1(x) _LV_SYMBOL_STR(_LV_SYMBOL_CHAR(x))
#define _LV_SYMBOL_VALUE3(x, y, z) _LV_SYMBOL_STR(_LV_SYMBOL_CHAR(x)_LV_SYMBOL_CHAR(y)_LV_SYMBOL_CHAR(z))

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /*LV_LV_SYMBOL_DEF_H*/
