/**
 * @file lvgl_private.h
 */

#ifndef LVGL_PRIVATE_SRC_H
#define LVGL_PRIVATE_SRC_H

#ifdef __cplusplus
extern "C" {
#endif

/*********************
 *      INCLUDES
 *********************/

/* Give access to the public API from the private API */
#include "lvgl_public.h"

#include "core/lv_global.h"
#include "core/lv_group_private.h"
#include "core/lv_obj_class_private.h"
#include "core/lv_obj_draw_private.h"
#include "core/lv_obj_event_private.h"
#include "core/lv_obj_private.h"
#include "core/lv_obj_scroll_private.h"
#include "core/lv_obj_style_private.h"
#include "core/lv_observer_private.h"
#include "core/lv_refr_private.h"
#include "debugging/monkey/lv_monkey_private.h"
#include "debugging/sysmon/lv_sysmon_private.h"
#include "debugging/test/lv_test_private.h"
#include "display/lv_display_private.h"
#include "draw/convert/helium/lv_draw_buf_convert_helium.h"
#include "draw/convert/lv_draw_buf_convert.h"
#include "draw/convert/neon/lv_draw_buf_convert_neon.h"
#include "draw/dma2d/lv_draw_dma2d.h"
#include "draw/dma2d/lv_draw_dma2d_private.h"
#include "draw/espressif/ppa/lv_draw_ppa.h"
#include "draw/espressif/ppa/lv_draw_ppa_private.h"
#include "draw/eve/lv_draw_eve.h"
#include "draw/eve/lv_draw_eve_private.h"
#include "draw/eve/lv_draw_eve_ram_g.h"
#include "draw/eve/lv_eve.h"
#include "draw/lv_draw_buf_private.h"
#include "draw/lv_draw_image_private.h"
#include "draw/lv_draw_label_private.h"
#include "draw/lv_draw_private.h"
#include "draw/lv_draw_vector_private.h"
#include "draw/lv_image_decoder_private.h"
#include "draw/nanovg/lv_draw_nanovg.h"
#include "draw/nanovg/lv_draw_nanovg_private.h"
#include "draw/nanovg/lv_nanovg_fbo_cache.h"
#include "draw/nanovg/lv_nanovg_image_cache.h"
#include "draw/nanovg/lv_nanovg_math.h"
#include "draw/nanovg/lv_nanovg_utils.h"
#include "draw/nema_gfx/lv_draw_nema_gfx.h"
#include "draw/nema_gfx/lv_draw_nema_gfx_utils.h"
#include "draw/nema_gfx/lv_nema_gfx_path.h"
#include "draw/nxp/g2d/lv_draw_g2d.h"
#include "draw/nxp/g2d/lv_g2d_buf_map.h"
#include "draw/nxp/g2d/lv_g2d_utils.h"
#include "draw/nxp/pxp/lv_draw_pxp.h"
#include "draw/nxp/pxp/lv_pxp_cfg.h"
#include "draw/nxp/pxp/lv_pxp_osa.h"
#include "draw/nxp/pxp/lv_pxp_utils.h"
#include "draw/opengles/lv_draw_opengles.h"
#include "draw/renesas/dave2d/lv_draw_dave2d.h"
#include "draw/renesas/dave2d/lv_draw_dave2d_utils.h"
#include "draw/sdl/lv_draw_sdl.h"
#include "draw/sw/arm2d/lv_draw_sw_arm2d.h"
#include "draw/sw/arm2d/lv_draw_sw_helium.h"
#include "draw/sw/blend/arm2d/lv_blend_arm2d.h"
#include "draw/sw/blend/helium/lv_blend_helium.h"
#include "draw/sw/blend/lv_draw_sw_blend.h"
#include "draw/sw/blend/lv_draw_sw_blend_private.h"
#include "draw/sw/blend/lv_draw_sw_blend_to_a8.h"
#include "draw/sw/blend/lv_draw_sw_blend_to_al88.h"
#include "draw/sw/blend/lv_draw_sw_blend_to_argb8888.h"
#include "draw/sw/blend/lv_draw_sw_blend_to_argb8888_premultiplied.h"
#include "draw/sw/blend/lv_draw_sw_blend_to_i1.h"
#include "draw/sw/blend/lv_draw_sw_blend_to_l8.h"
#include "draw/sw/blend/lv_draw_sw_blend_to_rgb565.h"
#include "draw/sw/blend/lv_draw_sw_blend_to_rgb565_swapped.h"
#include "draw/sw/blend/lv_draw_sw_blend_to_rgb888.h"
#include "draw/sw/blend/neon/lv_blend_neon.h"
#include "draw/sw/blend/neon/lv_draw_sw_blend_neon_to_rgb565.h"
#include "draw/sw/blend/neon/lv_draw_sw_blend_neon_to_rgb888.h"
#include "draw/sw/blend/riscv_v/lv_blend_riscv_v.h"
#include "draw/sw/blend/riscv_v/lv_blend_riscv_v_private.h"
#include "draw/sw/blend/riscv_v/lv_blend_riscv_vector_emulation.h"
#include "draw/sw/blend/riscv_v/lv_draw_sw_blend_riscv_v_to_rgb888.h"
#include "draw/sw/lv_draw_sw.h"
#include "draw/sw/lv_draw_sw_grad.h"
#include "draw/sw/lv_draw_sw_mask.h"
#include "draw/sw/lv_draw_sw_mask_private.h"
#include "draw/sw/lv_draw_sw_private.h"
#include "draw/vg_lite/lv_draw_vg_lite.h"
#include "draw/vg_lite/lv_draw_vg_lite_type.h"
#include "draw/vg_lite/lv_vg_lite_bitmap_font_cache.h"
#include "draw/vg_lite/lv_vg_lite_decoder.h"
#include "draw/vg_lite/lv_vg_lite_grad.h"
#include "draw/vg_lite/lv_vg_lite_math.h"
#include "draw/vg_lite/lv_vg_lite_path.h"
#include "draw/vg_lite/lv_vg_lite_pending.h"
#include "draw/vg_lite/lv_vg_lite_stroke.h"
#include "draw/vg_lite/lv_vg_lite_utils.h"
#include "drivers/display/drm/lv_linux_drm_egl_private.h"
#include "drivers/display/ft81x/lv_ft81x_defines.h"
#include "drivers/evdev/lv_evdev_private.h"
#include "drivers/libinput/lv_libinput_private.h"
#include "drivers/libinput/lv_xkb_private.h"
#include "drivers/nuttx/lv_nuttx_cache.h"
#include "drivers/nuttx/lv_nuttx_image_cache.h"
#include "drivers/nuttx/lv_nuttx_mouse.h"
#include "drivers/nuttx/lv_nuttx_profiler.h"
#include "drivers/opengles/assets/lv_opengles_shader.h"
#include "drivers/opengles/lv_opengles_debug.h"
#include "drivers/opengles/lv_opengles_egl.h"
#include "drivers/opengles/lv_opengles_egl_private.h"
#include "drivers/opengles/lv_opengles_private.h"
#include "drivers/opengles/lv_opengles_texture_private.h"
#include "drivers/opengles/opengl_shader/lv_opengl_shader_internal.h"
#include "drivers/sdl/lv_sdl_private.h"
#include "drivers/uefi/lv_uefi_private.h"
#include "drivers/wayland/lv_wayland_backend_private.h"
#include "drivers/wayland/lv_wayland_private.h"
#include "drivers/windows/lv_windows_context.h"
#include "drivers/windows/lv_windows_input_private.h"
#include "font/fmt_txt/lv_font_fmt_txt_private.h"
#include "font/font_manager/lv_font_manager_recycle.h"
#include "font/lv_font_private.h"
#include "indev/lv_indev_gesture_private.h"
#include "indev/lv_indev_private.h"
#include "indev/lv_indev_scroll.h"
#include "layouts/lv_layout_private.h"
#include "libs/barcode/lv_barcode_private.h"
#include "libs/ffmpeg/lv_ffmpeg_private.h"
#include "libs/freetype/lv_freetype_private.h"
#include "libs/gltf/gltf_data/lv_gltf_data_internal.h"
#include "libs/gltf/gltf_environment/lv_gltf_environment_private.h"
#include "libs/gltf/gltf_view/assets/lv_gltf_view_shader.h"
#include "libs/gltf/gltf_view/lv_gltf_view_internal.h"
#include "libs/gstreamer/lv_gstreamer_internal.h"
#include "libs/qrcode/lv_qrcode_private.h"
#include "libs/rle/lv_rle_private.h"
#include "libs/rlottie/lv_rlottie_private.h"
#include "libs/svg/lv_svg_decoder.h"
#include "libs/svg/lv_svg_parser.h"
#include "libs/svg/lv_svg_render.h"
#include "libs/svg/lv_svg_token.h"
#include "misc/cache/class/lv_cache_class.h"
#include "misc/cache/class/lv_cache_lru_ll.h"
#include "misc/cache/class/lv_cache_lru_rb.h"
#include "misc/cache/class/lv_cache_sc_da.h"
#include "misc/cache/instance/lv_cache_instance.h"
#include "misc/cache/instance/lv_image_cache.h"
#include "misc/cache/instance/lv_image_header_cache.h"
#include "misc/cache/lv_cache.h"
#include "misc/cache/lv_cache_entry.h"
#include "misc/cache/lv_cache_entry_private.h"
#include "misc/lv_anim_private.h"
#include "misc/lv_anim_timeline_private.h"
#include "misc/lv_area_private.h"
#include "misc/lv_bidi_private.h"
#include "misc/lv_circle_buf_private.h"
#include "misc/lv_event_private.h"
#include "misc/lv_fs_private.h"
#include "misc/lv_iter_private.h"
#include "misc/lv_lru.h"
#include "misc/lv_pending.h"
#include "misc/lv_profiler_builtin_private.h"
#include "misc/lv_rb_private.h"
#include "misc/lv_templ.h"
#include "misc/lv_text_ap.h"
#include "misc/lv_text_private.h"
#include "misc/lv_timer_private.h"
#include "misc/lv_utils.h"
#include "osal/lv_cmsis_rtos2.h"
#include "osal/lv_freertos.h"
#include "osal/lv_linux.h"
#include "osal/lv_mqx.h"
#include "osal/lv_os_none.h"
#include "osal/lv_os_private.h"
#include "osal/lv_pthread.h"
#include "osal/lv_rtthread.h"
#include "osal/lv_sdl2.h"
#include "osal/lv_windows.h"
#include "others/file_explorer/lv_file_explorer_private.h"
#include "others/fragment/lv_fragment_private.h"
#include "others/translation/lv_translation_private.h"
#include "stdlib/builtin/lv_tlsf.h"
#include "stdlib/builtin/lv_tlsf_private.h"
#include "themes/lv_theme_private.h"
#include "tick/lv_tick_private.h"
#include "widgets/3dtexture/lv_3dtexture_private.h"
#include "widgets/animimage/lv_animimage_private.h"
#include "widgets/arc/lv_arc_private.h"
#include "widgets/arclabel/lv_arclabel_private.h"
#include "widgets/bar/lv_bar_private.h"
#include "widgets/button/lv_button_private.h"
#include "widgets/buttonmatrix/lv_buttonmatrix_private.h"
#include "widgets/calendar/lv_calendar_private.h"
#include "widgets/canvas/lv_canvas_private.h"
#include "widgets/chart/lv_chart_private.h"
#include "widgets/checkbox/lv_checkbox_private.h"
#include "widgets/dropdown/lv_dropdown_private.h"
#include "widgets/image/lv_image_private.h"
#include "widgets/imagebutton/lv_imagebutton_private.h"
#include "widgets/ime/lv_ime_pinyin_private.h"
#include "widgets/keyboard/lv_keyboard_private.h"
#include "widgets/label/lv_label_private.h"
#include "widgets/led/lv_led_private.h"
#include "widgets/line/lv_line_private.h"
#include "widgets/lottie/lv_lottie_private.h"
#include "widgets/menu/lv_menu_private.h"
#include "widgets/msgbox/lv_msgbox_private.h"
#include "widgets/objx_templ/lv_objx_templ.h"
#include "widgets/roller/lv_roller_private.h"
#include "widgets/scale/lv_scale_private.h"
#include "widgets/slider/lv_slider_private.h"
#include "widgets/span/lv_span_private.h"
#include "widgets/spinbox/lv_spinbox_private.h"
#include "widgets/spinner/lv_spinner_private.h"
#include "widgets/switch/lv_switch_private.h"
#include "widgets/table/lv_table_private.h"
#include "widgets/tabview/lv_tabview_private.h"
#include "widgets/textarea/lv_textarea_private.h"
#include "widgets/tileview/lv_tileview_private.h"
#include "widgets/win/lv_win_private.h"

/*********************
 *      DEFINES
 *********************/

/**********************
 *      TYPEDEFS
 **********************/

/**********************
 * GLOBAL PROTOTYPES
 **********************/

/**********************
 *      MACROS
 **********************/

#ifdef __cplusplus
} /*extern "C"*/
#endif
#endif /* LVGL_PRIVATE_SRC_H */
