/**
 * @file lv_snapshot.c
 *
 */

/*********************
 *      INCLUDES
 *********************/
#include <stdbool.h>

#include "lv_snapshot.h"
#include "../core/lv_disp.h"
#include "../core/lv_refr.h"
/*********************
 *      DEFINES
 *********************/

/**********************
 *      TYPEDEFS
 **********************/

/**********************
 *  STATIC PROTOTYPES
 **********************/

/**********************
 *  STATIC VARIABLES
 **********************/

/**********************
 *      MACROS
 **********************/

/**********************
 *   GLOBAL FUNCTIONS
 **********************/

/** Take snapshot for object with its children.
 *
 * @note The function will change the order obj in its parent.
 *
 * @param obj    The object to generate snapshot.
 * @param cf     color format for generated image.
 *
 * @return a pointer to a image descriptor, or NULL if failed.
 */
lv_img_dsc_t * lv_snapshot_take(lv_obj_t * obj, lv_img_cf_t cf)
{
    switch(cf) {
        case LV_IMG_CF_TRUE_COLOR_ALPHA:
        case LV_IMG_CF_ALPHA_1BIT:
        case LV_IMG_CF_ALPHA_2BIT:
        case LV_IMG_CF_ALPHA_4BIT:
        case LV_IMG_CF_ALPHA_8BIT:
            break;
        default:
            return NULL;
    }

    /*Backup obj original info.*/
    lv_disp_t * disp_old = lv_obj_get_disp(obj);
    lv_obj_t * parent_old = lv_obj_get_parent(obj);

    lv_obj_update_layout(obj);

    /*Width and height determine snapshot image size.*/
    lv_coord_t w = lv_obj_get_width(obj);
    lv_coord_t h = lv_obj_get_height(obj);

    uint8_t px_size = lv_img_cf_get_px_size(cf);
    uint32_t buff_size = w * h * ((px_size + 7) >> 3);
    void * buff = lv_mem_alloc(buff_size);
    if(buff == NULL) {
        return NULL;
    }

    lv_img_dsc_t * dsc = lv_mem_alloc(sizeof(lv_img_dsc_t));
    if(dsc == NULL) {
        lv_mem_free(buff);
        return NULL;
    }
    lv_memset(buff, 0x00, buff_size);
    lv_memset_00(dsc, sizeof(lv_img_dsc_t));

    /*We are safe to use stack for below variables since disp will be
     * unregistered when function returns. */
    lv_disp_t * disp;
    lv_disp_drv_t driver;
    lv_disp_draw_buf_t draw_buf;

    lv_disp_draw_buf_init(&draw_buf, buff, NULL, w * h);

    lv_disp_drv_init(&driver);
    driver.draw_buf = &draw_buf;
    driver.hor_res = lv_disp_get_hor_res(disp_old);
    driver.ver_res = lv_disp_get_ver_res(disp_old);
    lv_disp_drv_use_generic_set_px_cb(&driver, cf);

    disp = lv_disp_drv_register(&driver);
    if(disp == NULL) {
        lv_mem_free(buff);
        lv_mem_free(dsc);
        return NULL;
    }

    /*Make background transparent */
    lv_disp_set_bg_opa(disp, LV_OPA_TRANSP);

    /*Move obj to newly created disp and refresh it. */
    lv_obj_t * screen = lv_disp_get_scr_act(disp);
    lv_obj_remove_style_all(screen);
    lv_obj_allocate_spec_attr(screen);
    screen->spec_attr->child_cnt = 1;
    screen->spec_attr->children = &obj;

    obj->parent = screen;

    /*Display buffer targets to position 0, 0 */
    disp->inv_p = 0;
    lv_obj_invalidate(obj);

    /*Don't call lv_refr_now to avoid animation disruption */
    _lv_disp_refr_timer(disp->refr_timer);

    /*Restore obj original parameters and clean up*/
    obj->parent = parent_old;
    screen->spec_attr->child_cnt = 0;
    screen->spec_attr->children = NULL;

    lv_disp_remove(disp);

    dsc->data = buff;
    dsc->header.w = w;
    dsc->header.h = h;
    dsc->header.cf = cf;
    return dsc;
}

/** Free the snapshot image returned by @ref lv_snapshot_take
 *
 * It will firstly free the data image takes, then the image descriptor.
 *
 * @param dsc    The image descriptor generated by lv_snapshot_take.
 *
 */
void lv_snapshot_free(lv_img_dsc_t * dsc)
{
    if(!dsc)
        return;

    if(dsc->data)
        lv_mem_free((void *)dsc->data);

    lv_mem_free(dsc);
}

/**********************
 *   STATIC FUNCTIONS
 **********************/
