name: Hardware Build Test

on:
  push:
    branches: 'master'
  pull_request:
    branches: 'master'

jobs:
  run_benchmark:
    runs-on: self-hosted
    name: Hardware Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install EJ dispatcher tool
        run: |
          cargo install ejlv

      - name: Dispatch job
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            REPO_URL="${{ github.event.pull_request.head.repo.clone_url }}"
            COMMIT_REF="${{ github.event.pull_request.head.sha }}"
          else
            REPO_URL="${{ github.server_url }}/${{ github.repository }}"
            COMMIT_REF="${{ github.sha }}"
          fi

          ejlv dispatch-build \
            --socket /ejd/ejd.sock \
            --commit-hash $COMMIT_REF \
            --remote-url $REPO_URL \
            --seconds 600
