name: Emulated Performance Test Results Handler

on:
  workflow_run:
    workflows: [Emulated Performance Test]
    types:
      - completed
  
concurrency:
  group: ${{ github.event.workflow_run.event }}-${{ github.event.workflow_run.head_branch }}-${{ github.workflow }} 
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  check_scripts:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'master' }}
    runs-on: ubuntu-24.04
    name: ARM Emulated Benchmark - Script Check
    strategy:
      fail-fast: false
      matrix: 
        test_script:
          - scripts/perf/tests/serialize_results/test.sh
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Check Script
        run: |
          pip3 install msgpack==1.1.0
          ./${{ matrix.test_script }}

  handle_results:
    needs: check_scripts
    runs-on: ubuntu-24.04
    name: ARM Emulated Benchmark - Handle Results
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Download Results from master
        uses: dawidd6/action-download-artifact@v24
        with:
          workflow: perf_emulation.yml
          path: artifacts
          allow_forks: false

      - name: Move JSON files to a single folder
        run: |
          mkdir input
          find artifacts -name "*.json" -exec mv {} input/ \;

      - name: Collect 'master' Results
        uses: robinraju/release-downloader@v1
        continue-on-error: true # The release may not exist yet
        with:
          preRelease: true
          tag: emulated-benchmark-latest
          fileName: results*.mpk

      - name: Serialize Results
        run: |
          # Here the input folder already exists from a previous step
          pip3 install msgpack==1.1.0
          mkdir output
          find . -maxdepth 1 \( -name "results*.mpk" \) -exec mv -t input {} +
          python scripts/perf/serialize_results.py --input input --output output --commit-hash ${{ github.sha }}

      - name: Store Results in Benchmark Release
        uses: softprops/action-gh-release@v3
        with:
          name: Emulated Benchmark Latest
          files: output/results*.mpk
          tag_name: emulated-benchmark-latest
          prerelease: true
          body: This pre-release is automatically generated and serves as a repository for benchmark results.
